name: Script Workflow

on:
  workflow_dispatch:

jobs:
  script-workflow:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Script workflow
        run: |
          echo "Hello, script workflow"

      - name: Run js Script
        run: node script.js
        