name: Matrix workflow

on:
  workflow_dispatch:

jobs:
  matrix-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        uppercase: [A, B, C]
        lowercase: [a, b, c]

    steps:
      - name: Echo Message
        run: echo "running matrix"

      - name: print matrix array
        run: echo ${{matrix.uppercase}}
      
      - name: print all matrix
        run: |
          echo "Matrix is: ${{matrix.uppercase}} ${{matrix.lowercase}}"